# Config settings
title: Jekyll Random Redirect Demo
baseurl: "/random_food"

# Random redirect settings
random_redirect:
  pages: true

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
